apiVersion: v1
kind: Pod
metadata:
  name: pod-tolerance
  labels:
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
  - key: "hardware"
    value: "gpu"
    operator: "Equal"
    effect: "NoExecute"
  nodeSelector:
    project: roboshop