apiVersion: v1
kind: Pod
metadata:
  name: node-affinitytest
  labels:
    project: roboshop
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - us-east-1a
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80